### ISSUE TITLE
Update Broke It :(

### ISSUE THREAD

**Issue by seraphlin** [carlos1172/ProgressBarTimeLeft#11]
Hi, I updated this add-on and it stopped working! Anki gives an error and the progress bar is now black and blank. If there is no current fix for it, could we please get the previous version for now? That one worked very well!

**Comment by seraphlin** [comment]
The error I get:

Traceback (most recent call last):
  File "aqt.main", line 574, in loadCollection
  File "aqt.main", line 676, in moveToState
  File "aqt.hooks_gen", line 3797, in __call__
  File "anki.hooks", line 34, in runHook
  File "/Users/seraphlin/Library/Application Support/Anki2/addons21/1097423555/reviewer_progress_bar.py", line 853, in afterStateChangeCallBack
    updatePB()
  File "/Users/seraphlin/Library/Application Support/Anki2/addons21/1097423555/reviewer_progress_bar.py", line 347, in updatePB
    xTR = 1-float(passed/(float(passed+flunked)))
ZeroDivisionError: float division by zero

**Comment by carlos1172** [comment]
Okay will work on this when I have time.

**Comment by carlos1172** [comment]
Done. Please see if it is fixed.

**Comment by seraphlin** [comment]
Yeah!! It works now! Thank you so much! This is a wonderful add-on :D

**Comment by carlos1172** [comment]
You’re welcome. Feel free to leave feedback at https://ankiweb.net/shared/info/1097423555

:)
