### ISSUE TITLE
Progress bar all blacked out

### ISSUE THREAD

**Issue by tb9198** [carlos1172/ProgressBarTimeLeft#13]
Hello! Really enjoy your addon. But it has some problem since the update on 7/21. The progress bar is all blacked out.

this is what error says:
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2022-07-27 17:41:57
Add-ons possibly involved: ⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 54, in handler
  File "aqt/main.py", line 150, in on_window_init
  File "aqt/hooks_gen.py", line 2602, in __call__
  File "/Users/ianthienbui/Library/Application Support/Anki2/addons21/1097423555/reviewer_progress_bar.py", line 169, in add_info
    x = (mw.col.sched.day_cutoff - 86400 * no_days) * 1000
AttributeError: 'NoneType' object has no attribute 'sched'

**Comment by carlos1172** [comment]
Try updating Anki

**Comment by tb9198** [comment]
Updated the anki to the newer version. Now the entire bar is blue as if i finished the deck. Look below:
----------------
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.4
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2022-07-28 15:26:16
Add-ons possibly involved: ⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 198, in on_window_init
  File "aqt.hooks_gen", line 2801, in __call__
  File "/Users/ianthienbui/Library/Application Support/Anki2/addons21/1097423555/reviewer_progress_bar.py", line 169, in add_info
    x = (mw.col.sched.day_cutoff - 86400 * no_days) * 1000
AttributeError: 'NoneType' object has no attribute 'sched'

**Comment by carlos1172** [comment]
Are you on Qt5 or Qt6? What are the steps to reproduce the problem?

**Comment by khonkhortisan** [comment]
This error only happens when the select user profile dialog is allowed to show - when not running `anki.exe -p "User 1"`. There's no mw.col because it doesn't know whose collection.anki2 SQL database to use. I'm on Versión ⁨2.1.54 (b6a7760c)⁩ Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

**Comment by khonkhortisan** [comment]
In case someone else reads this issue looking for this cause:
```
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1097423555\reviewer_progress_bar.py", line 368, in updatePB
    left = dt.timestamp() + tzsec + t.total_seconds()
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```
I had a different cause for a black progress bar: `"tz": "8"` instead of `"tz": 8`, fixed by resetting the addon config through the menu.
