### ISSUE TITLE
When opening anki, an error will appear

### ISSUE THREAD

**Issue by Diplproveably** [carlos1172/ProgressBarTimeLeft#27]
```
加载⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩时：
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\周一飞\AppData\Roaming\Anki2\addons21\1097423555\__init__.py", line 1, in <module>
    from . import reviewer_progress_bar
  File "C:\Users\周一飞\AppData\Roaming\Anki2\addons21\1097423555\reviewer_progress_bar.py", line 596, in <module>
    toggle_sc = config['toggle_shortcut']
KeyError: 'toggle_shortcut'
⁩
```

**Comment by PatrickDrewsES** [comment]
Same here:

⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users//Library/Application Support/Anki2/addons21/1695607349/__init__.py", line 1, in <module>
    from . import reviewer_progress_bar
  File "/Users//Library/Application Support/Anki2/addons21/1695607349/reviewer_progress_bar.py", line 3, in <module>
    from .night_mode import isnightmode
ModuleNotFoundError: No module named '1695607349.night_mode'
⁩

**Comment by akavi1** [comment]
@carlos1172 can you merge #26

**Comment by BrachoDesu** [comment]
Hello there

Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\Ricardo\AppData\Roaming\Anki2\addons21\1097423555\__init__.py", line 1, in <module>
    from . import reviewer_progress_bar
  File "C:\Users\Ricardo\AppData\Roaming\Anki2\addons21\1097423555\reviewer_progress_bar.py", line 3, in <module>
    from .night_mode import isnightmode
ModuleNotFoundError: No module named '1097423555.night_mode'
⁩

**Comment by carlos1172** [comment]
When did you get the error? After updating?

Regards,
Carlos Miguel C. Resurreccion

**Comment by PatrickDrewsES** [comment]
Right, it occurred right after updating to the recent version.
