### ISSUE TITLE
KeyError: 'toggle_shortcut'

### ISSUE THREAD

**Issue by GrimPixel** [carlos1172/ProgressBarTimeLeft#28]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/home/user/.local/share/Anki2/addons21/1097423555/__init__.py", line 1, in <module>
    from . import reviewer_progress_bar
  File "/home/user/.local/share/Anki2/addons21/1097423555/reviewer_progress_bar.py", line 596, in <module>
    toggle_sc = config['toggle_shortcut']
KeyError: 'toggle_shortcut'
⁩

**Comment by GrimPixel** [comment]
It's a dup to https://github.com/carlos1172/ProgressBarTimeLeft/issues/27.
