### ISSUE TITLE
Toggle_shortcut

### ISSUE THREAD

**Issue by marlouis** [carlos1172/ProgressBarTimeLeft#29]
Hi, 

I see two open issues regarding the "toggle_shortcut" problem. Is there any solution to fix this ? 
Regards, 

Erreur
Un greffon que vous avez installé n’a pu se charger. Si le problème persiste, allez dans le menu Outils > Greffons et désactivez ou supprimez ce greffon.

Pendant le chargement de « ⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩ » :
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/josephdupont/Library/Application Support/Anki2/addons21/1097423555/__init__.py", line 1, in <module>
    from . import reviewer_progress_bar
  File "/Users/josephdupont/Library/Application Support/Anki2/addons21/1097423555/reviewer_progress_bar.py", line 596, in <module>
    toggle_sc = config['toggle_shortcut']
KeyError: 'toggle_shortcut'
⁩

**Comment by akavi1** [comment]
fix is in #26 . Someone just needs to merge it

**Comment by Hatzuki04** [comment]
Yo lo solucioné llendo a la configuración de complementos, seleccionas en  « ⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩ », luego le das clic en configuración y colocas:

`"toggle_shortcut": "Ctrl + Alt + P"`
