### ISSUE TITLE
ERROR ModuleNotFoundError: No module named '1097423555.night_mode'

### ISSUE THREAD

**Issue by Hatzuki04** [carlos1172/ProgressBarTimeLeft#31]
Me aparece este error y no sé cómo solucionarlo:

Error
Un complemento que has instalado ha fallado al cargarse. Si los problemas persisten, por favor ve a Herramientas> Menú de complementos o deshabilita este complemento.

Mientras cargando '⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\nicze\AppData\Roaming\Anki2\addons21\1097423555\__init__.py", line 1, in <module>
    from . import reviewer_progress_bar
  File "C:\Users\nicze\AppData\Roaming\Anki2\addons21\1097423555\reviewer_progress_bar.py", line 3, in <module>
    from .night_mode import isnightmode
ModuleNotFoundError: No module named '1097423555.night_mode'
⁩

**Comment by carlos1172** [comment]
Update your addon version

Regards,
Carlos Miguel C. Resurreccion

**Comment by nalanihuang** [comment]
I am also experiencing this issue! Sorry, how do you update an addon version? When I click check for updates, anki responds by saying there are no available.

**Comment by carlos1172** [comment]
Try now

Regards,
Carlos Miguel C. Resurreccion

**Comment by nalanihuang** [comment]
That worked, thank you!
