### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decks'

### ISSUE THREAD

**Issue by GrimPixel** [carlos1172/ProgressBarTimeLeft#6]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.50 (f84cc1d7) Python 3.10.4 Qt 6.3.0 PyQt 6.3.0
Platform: Linux
Flags: frz=False ao=True sv=?
Add-ons, last update check: 2022-04-23 11:48:25
Add-ons possibly involved: ⁨Progress Bar cards done cards left secondscard time spentleft and ETA⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/progress.py", line 115, in handler
    func()
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 186, in on_window_init
    fn()
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 277, in setupProfile
    self.showProfileManager()
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 283, in showProfileManager
    self.moveToState("profileManager")
  File "/usr/lib/python3.10/site-packages/aqt/main.py", line 672, in moveToState
    gui_hooks.state_did_change(state, oldState)
  File "/usr/lib/python3.10/site-packages/aqt/hooks_gen.py", line 3594, in __call__
    anki.hooks.runHook("afterStateChange", new_state, old_state)
  File "/usr/lib/python3.10/site-packages/anki/hooks.py", line 34, in runHook
    func(*args)
  File "/home/grim/.local/share/Anki2/addons21/1097423555/reviewer_progress_bar.py", line 402, in afterStateChangeCallBack
    currDID = mw.col.decks.current()['id']
AttributeError: 'NoneType' object has no attribute 'decks'

**Comment by carlos1172** [comment]
Can you try disabling all other addons?

**Comment by GrimPixel** [comment]
The problem is, Anki has some trouble with my system, and it doesn't even open.

**Comment by carlos1172** [comment]
I'm sorry, I don't know how to fix this :(

**Comment by carlos1172** [comment]
@GrimPixel Workaround right now is to not have multiple profiles open

**Comment by carlos1172** [comment]
fixed with BluMist's pull request
